/* ShellOS Quiz questions (original, for kids). Each item: [question, correct answer, wrong, wrong, wrong]. */
(function (root, factory) {
  if (typeof module === 'object' && module.exports) module.exports = factory();
  else root.QuizData = factory();
})(typeof self !== 'undefined' ? self : this, function () {
  'use strict';
  const CATS = [
    { id: 'animals', name: 'Animals', emoji: '🦁', color: '#ff9f0a' },
    { id: 'space', name: 'Space', emoji: '🚀', color: '#5e5ce6' },
    { id: 'geo', name: 'Geography', emoji: '🌍', color: '#34c759' },
    { id: 'math', name: 'Math', emoji: '➕', color: '#ff375f' },
    { id: 'science', name: 'Science', emoji: '🔬', color: '#0a84ff' }
  ];
  const Q = {
    animals: [
      ['What is the largest animal that has ever lived?', 'Blue whale', 'African elephant', 'Giraffe', 'Great white shark'],
      ['How many legs does a spider have?', '8', '6', '10', '4'],
      ['Which animal is known as the "King of the Jungle"?', 'Lion', 'Tiger', 'Gorilla', 'Elephant'],
      ['What do caterpillars turn into?', 'Butterflies or moths', 'Beetles', 'Bees', 'Spiders'],
      ['Which bird cannot fly but is a very fast runner?', 'Ostrich', 'Eagle', 'Parrot', 'Robin'],
      ['What is a baby kangaroo called?', 'A joey', 'A cub', 'A kid', 'A calf'],
      ['Which animal has black and white stripes?', 'Zebra', 'Leopard', 'Cheetah', 'Camel'],
      ['How many hearts does an octopus have?', '3', '1', '2', '8'],
      ['What is the tallest animal in the world?', 'Giraffe', 'Elephant', 'Horse', 'Moose'],
      ['Which animal sleeps hanging upside down?', 'Bat', 'Owl', 'Squirrel', 'Frog'],
      ['What do bees make?', 'Honey', 'Milk', 'Silk', 'Wax crayons'],
      ['A frog starts its life as a...', 'Tadpole', 'Caterpillar', 'Chick', 'Pup'],
      ['Which animal is the fastest on land?', 'Cheetah', 'Lion', 'Horse', 'Rabbit'],
      ['What do pandas mostly eat?', 'Bamboo', 'Fish', 'Berries', 'Grass'],
      ['Which sea animal has eight arms?', 'Octopus', 'Starfish', 'Crab', 'Jellyfish'],
      ['What is a group of fish called?', 'A school', 'A herd', 'A pack', 'A flock'],
      ['Which animal carries its house on its back?', 'Snail', 'Rabbit', 'Mouse', 'Duck'],
      ['Penguins live mostly in the...', 'Southern Hemisphere', 'North Pole', 'Sahara Desert', 'Amazon Rainforest'],
      ['What kind of animal is a dolphin?', 'A mammal', 'A fish', 'A reptile', 'An amphibian'],
      ['Which insect glows at night?', 'Firefly', 'Ladybug', 'Ant', 'Grasshopper'],
      ['How many humps does a dromedary camel have?', '1', '2', '3', 'None'],
      ['What does a herbivore eat?', 'Plants', 'Meat', 'Only fish', 'Rocks'],
      ['Which animal is famous for changing its skin color?', 'Chameleon', 'Crocodile', 'Turtle', 'Rabbit']
    ],
    space: [
      ['What is the closest star to Earth?', 'The Sun', 'The Moon', 'The North Star', 'Mars'],
      ['Which planet is known as the Red Planet?', 'Mars', 'Venus', 'Jupiter', 'Mercury'],
      ['What is the largest planet in our solar system?', 'Jupiter', 'Saturn', 'Earth', 'Neptune'],
      ['Which planet has beautiful rings made of ice and rock?', 'Saturn', 'Mars', 'Mercury', 'Venus'],
      ['How many planets are in our solar system?', '8', '7', '9', '10'],
      ['What do we call a person who travels into space?', 'Astronaut', 'Pilot', 'Sailor', 'Geologist'],
      ['Which planet is closest to the Sun?', 'Mercury', 'Venus', 'Earth', 'Mars'],
      ['What causes day and night on Earth?', 'Earth spinning', 'The Moon moving', 'Clouds', 'The Sun turning off'],
      ['About how long does Earth take to go around the Sun?', '1 year', '1 day', '1 month', '1 week'],
      ['What is the Moon made of?', 'Rock', 'Cheese', 'Ice cream', 'Gas'],
      ['Who was the first person to walk on the Moon?', 'Neil Armstrong', 'Albert Einstein', 'Isaac Newton', 'Amelia Earhart'],
      ['What is the name of our galaxy?', 'The Milky Way', 'The Big Dipper', 'Andromeda', 'The Solar Way'],
      ['Which planet do we live on?', 'Earth', 'Mars', 'Venus', 'Saturn'],
      ['What is a shooting star really?', 'A space rock burning up', 'A falling star', 'A firework', 'An airplane'],
      ['Which is the hottest planet in our solar system?', 'Venus', 'Mercury', 'Mars', 'Jupiter'],
      ['What shape is Earth?', 'Almost a sphere', 'Flat', 'A cube', 'A triangle'],
      ['What pulls things down toward the ground?', 'Gravity', 'Magnets', 'Wind', 'Light'],
      ['Which planet is famous for its Great Red Spot storm?', 'Jupiter', 'Mars', 'Uranus', 'Earth'],
      ['What do we call the Moon when it looks like a full circle?', 'Full moon', 'New moon', 'Half moon', 'Blue sun'],
      ['Which planet spins on its side?', 'Uranus', 'Earth', 'Mars', 'Venus'],
      ['What is the Sun?', 'A star', 'A planet', 'A moon', 'A comet'],
      ['What do astronauts wear to breathe on a spacewalk?', 'A spacesuit', 'A raincoat', 'A snorkel', 'Pajamas']
    ],
    geo: [
      ['What is the largest ocean on Earth?', 'Pacific Ocean', 'Atlantic Ocean', 'Indian Ocean', 'Arctic Ocean'],
      ['How many continents are there?', '7', '5', '6', '9'],
      ['Which continent is the coldest?', 'Antarctica', 'Europe', 'Asia', 'Africa'],
      ['What is the longest river in Africa?', 'The Nile', 'The Amazon', 'The Mississippi', 'The Thames'],
      ['What is the tallest mountain above sea level?', 'Mount Everest', 'Mount Fuji', 'Mount Kilimanjaro', 'Mount Rushmore'],
      ['What is the capital of the United States?', 'Washington, D.C.', 'New York City', 'Los Angeles', 'Chicago'],
      ['Which country is shaped like a boot?', 'Italy', 'Spain', 'Japan', 'Brazil'],
      ['What is the largest desert that is hot and sandy?', 'The Sahara', 'The Gobi', 'The Mojave', 'Death Valley'],
      ['In which country are the ancient pyramids of Giza?', 'Egypt', 'Mexico', 'China', 'Greece'],
      ['Which is the largest country by area?', 'Russia', 'Canada', 'China', 'Brazil'],
      ['What is the capital of France?', 'Paris', 'London', 'Rome', 'Madrid'],
      ['The Great Wall is in which country?', 'China', 'India', 'Japan', 'Peru'],
      ['Which continent is Kenya in?', 'Africa', 'Asia', 'South America', 'Europe'],
      ['What is a piece of land with water all around it?', 'An island', 'A valley', 'A canyon', 'A desert'],
      ['Which country has the most kangaroos?', 'Australia', 'Canada', 'Brazil', 'Norway'],
      ['What is the capital of Japan?', 'Tokyo', 'Beijing', 'Seoul', 'Bangkok'],
      ['What is the biggest rainforest in the world?', 'The Amazon', 'The Sahara', 'The Arctic', 'The Alps'],
      ['Which direction does the Sun rise in?', 'East', 'West', 'North', 'South'],
      ['What do we call a map of the whole world shaped like a ball?', 'A globe', 'A compass', 'A telescope', 'An atlas page'],
      ['Which ocean is between Europe and North America?', 'Atlantic Ocean', 'Pacific Ocean', 'Indian Ocean', 'Southern Ocean'],
      ['What is the capital of Canada?', 'Ottawa', 'Toronto', 'Vancouver', 'Montreal'],
      ['Mount Kilimanjaro is on which continent?', 'Africa', 'Asia', 'Europe', 'Australia']
    ],
    math: [
      ['What is 7 + 8?', '15', '14', '16', '13'],
      ['What is 9 × 3?', '27', '24', '21', '30'],
      ['How many sides does a triangle have?', '3', '4', '5', '6'],
      ['What is 20 − 7?', '13', '12', '14', '17'],
      ['How many minutes are in one hour?', '60', '100', '30', '24'],
      ['What is half of 18?', '9', '8', '6', '12'],
      ['How many sides does a hexagon have?', '6', '5', '7', '8'],
      ['What is 5 × 5?', '25', '10', '20', '55'],
      ['Which number is even?', '14', '7', '9', '11'],
      ['What is 100 − 45?', '55', '65', '45', '50'],
      ['How many days are in a week?', '7', '5', '10', '6'],
      ['What is 12 ÷ 4?', '3', '4', '6', '2'],
      ['What comes next: 2, 4, 6, 8, ...?', '10', '9', '12', '11'],
      ['How many cents make one dollar?', '100', '10', '50', '1,000'],
      ['What is 6 × 7?', '42', '36', '48', '49'],
      ['A square has how many corners?', '4', '3', '5', '8'],
      ['What is 3 + 3 + 3 + 3?', '12', '9', '15', '10'],
      ['How many months are in a year?', '12', '10', '11', '13'],
      ['What is 1,000 + 1,000?', '2,000', '1,100', '10,000', '3,000'],
      ['Which is bigger: 0.5 or 0.25?', '0.5', '0.25', 'They are equal', 'Neither'],
      ['What is 8 × 8?', '64', '56', '72', '48'],
      ['How many hours are in one day?', '24', '12', '60', '20'],
      ['What shape is a ball?', 'Sphere', 'Cube', 'Cone', 'Pyramid']
    ],
    science: [
      ['What gas do plants take in from the air to make food?', 'Carbon dioxide', 'Oxygen', 'Helium', 'Hydrogen'],
      ['What is water called when it freezes?', 'Ice', 'Steam', 'Fog', 'Sand'],
      ['At what temperature does water freeze in Celsius?', '0 degrees', '10 degrees', '100 degrees', '32 degrees'],
      ['What part of the plant soaks up water from the soil?', 'Roots', 'Petals', 'Leaves', 'Seeds'],
      ['How many bones are in the adult human body?', '206', '106', '306', '56'],
      ['What organ pumps blood around your body?', 'The heart', 'The lungs', 'The stomach', 'The brain'],
      ['What do we call water falling from clouds?', 'Rain', 'Wind', 'Thunder', 'Lightning'],
      ['What is the hardest natural material?', 'Diamond', 'Gold', 'Wood', 'Glass'],
      ['Which sense do you use your nose for?', 'Smell', 'Taste', 'Touch', 'Hearing'],
      ['What do magnets attract?', 'Iron and steel', 'Wood', 'Paper', 'Plastic'],
      ['What are the three states of matter we see most?', 'Solid, liquid, gas', 'Hot, warm, cold', 'Big, medium, small', 'Red, green, blue'],
      ['What do we breathe in to stay alive?', 'Oxygen', 'Carbon dioxide', 'Steam', 'Smoke'],
      ['What makes a rainbow?', 'Sunlight and raindrops', 'Paint in the sky', 'Wind', 'The Moon'],
      ['What is the center of an atom called?', 'The nucleus', 'The shell', 'The core crust', 'The orbit'],
      ['Which organ helps you think?', 'The brain', 'The liver', 'The heart', 'The skin'],
      ['What does a thermometer measure?', 'Temperature', 'Weight', 'Length', 'Time'],
      ['Sound travels in...', 'Waves', 'Straight sticks', 'Bubbles', 'Boxes'],
      ['What color do you get mixing blue and yellow paint?', 'Green', 'Purple', 'Orange', 'Pink'],
      ['What is the boiling point of water at sea level in Celsius?', '100 degrees', '50 degrees', '0 degrees', '212 degrees'],
      ['Which tool helps you see tiny things up close?', 'Microscope', 'Telescope', 'Periscope', 'Stethoscope'],
      ['What kind of energy comes from the Sun?', 'Solar energy', 'Wind energy', 'Geothermal energy', 'Coal energy'],
      ['What do we call animals that are active at night?', 'Nocturnal', 'Aquatic', 'Arctic', 'Domestic']
    ]
  };
  return { CATS, Q };
});
